### ISSUE TITLE
"Packages" doesn't work.

### ISSUE THREAD

**Issue by ogaoga** [rakuten-frontend/bower-browser#9]
When I selected "Packages" in the left-side menu, the error was output.

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at V (http://localhost:3010/assets/scripts/app.js:3:9299)
    at on (http://localhost:3010/assets/scripts/app.js:4:11870)
    at http://localhost:3010/assets/scripts/app.js:4:12297
    at o (http://localhost:3010/assets/scripts/app.js:3:5441)
    at cn (http://localhost:3010/assets/scripts/app.js:4:12307)
    at i (http://localhost:3010/assets/scripts/app.js:4:12887)
    at u (http://localhost:3010/assets/scripts/app.js:4:30849)
    at http://localhost:3010/assets/scripts/app.js:4:31021
    at h.$get.h.$eval (http://localhost:3010/assets/scripts/app.js:5:6161)
```
- v0.6.0
- Chrome Version 41.0.2272.101 (64-bit)
- OSX 10.10.1 (14B25)

In addition, I found the response of "bower-component-list.json" seems to be invalid. I checked it with `curl http://localhost:3010/api/bower-component-list.json -O`.

It occurs around https://github.com/rakuten-frontend/bower-browser/blob/master/client/assets/scripts/services/search.js#L86

**Comment by htanjo** [comment]
Make sure your network connection and run: `$ bower-browser --cache 0`.
This will re-fetch the API data.

**Comment by ogaoga** [comment]
Thanks! I'll try tomorrow.

**Comment by ogaoga** [comment]
It works well after clearing the cache. Thanks!
